# Generated by Django 5.1.2 on 2024-11-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_beneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
