# Generated by Django 5.1.2 on 2024-11-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_donate_is_perishable_donate_shelf_life_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='unit',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
