# Generated by Django 5.1.2 on 2024-11-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_donate_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='shelf_life',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
