# Generated by Django 5.1.2 on 2024-11-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_customuser_dark_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('twitter', models.URLField()),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
                ('linkedin', models.URLField()),
                ('youtube', models.URLField()),
            ],
            options={
                'verbose_name': 'Social Handler',
                'verbose_name_plural': 'Social Handlers',
            },
        ),
    ]
